# SPDX-FileCopyrightText: 2021 Serokell <https://serokell.io/>
#
# SPDX-License-Identifier: CC0-1.0

steps:
  - label: Check Nix flake
    commands:
      - nix-shell --run 'nix flake check -L'
  - label: Check Terraform
    commands:
      - nix-shell --run 'cd terraform && terraform init -backend=false && terraform validate'
